Ruby
http://www.cheat-sheets.org/saved-copy/RubyCheat.pdf
http://overapi.com/ruby/
참고
http://www.cheat-sheets.org
http://overapi.com
http://hyperpolyglot.org/
Python
https://perso.limsi.fr/pointal/_media/python:cours:mementopython3-english.pdf
http://www.cheat-sheets.org/saved-copy/PQRC-2.4-A4-latest.pdf
http://overapi.com/python/
